
package customerws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ImplServiceUserService", targetNamespace = "http://service.sms.acedwdev.com.co/", wsdlLocation = "http://localhost:8080/ImplServiceUserService/ImplServiceUser?wsdl")
public class ImplServiceUserService
    extends Service
{

    private final static URL IMPLSERVICEUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMPLSERVICEUSERSERVICE_EXCEPTION;
    private final static QName IMPLSERVICEUSERSERVICE_QNAME = new QName("http://service.sms.acedwdev.com.co/", "ImplServiceUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ImplServiceUserService/ImplServiceUser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMPLSERVICEUSERSERVICE_WSDL_LOCATION = url;
        IMPLSERVICEUSERSERVICE_EXCEPTION = e;
    }

    public ImplServiceUserService() {
        super(__getWsdlLocation(), IMPLSERVICEUSERSERVICE_QNAME);
    }

    public ImplServiceUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMPLSERVICEUSERSERVICE_QNAME, features);
    }

    public ImplServiceUserService(URL wsdlLocation) {
        super(wsdlLocation, IMPLSERVICEUSERSERVICE_QNAME);
    }

    public ImplServiceUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMPLSERVICEUSERSERVICE_QNAME, features);
    }

    public ImplServiceUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImplServiceUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServiceWs
     */
    @WebEndpoint(name = "ImplServiceUserPort")
    public UserServiceWs getImplServiceUserPort() {
        return super.getPort(new QName("http://service.sms.acedwdev.com.co/", "ImplServiceUserPort"), UserServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceWs
     */
    @WebEndpoint(name = "ImplServiceUserPort")
    public UserServiceWs getImplServiceUserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sms.acedwdev.com.co/", "ImplServiceUserPort"), UserServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMPLSERVICEUSERSERVICE_EXCEPTION!= null) {
            throw IMPLSERVICEUSERSERVICE_EXCEPTION;
        }
        return IMPLSERVICEUSERSERVICE_WSDL_LOCATION;
    }

}
